name: docker job and secrets
on: push
jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
      - name: docker build
        # environment variables can be in step, job and repository level
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USER_NAME: abinash0051
          IMAGE_NAME: github-actions-nginx
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USER_NAME/$IMAGE_NAME:latest