name: docker job and secrets
on: push
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
      - name: docker build
        # environment variables can be in step, job and repository level
        run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USER_NAME }}/$IMAGE_NAME:latest

      - name: docker login
        run: echo docker login --username=${{ vars.DOCKER_USER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: docker publish
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USER_NAME: abinash0051
          IMAGE_NAME: github-actions-nginx
        run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USER_NAME }}/$IMAGE_NAME:latest