# Name of the workflow
name: my first workflow

# This is a trigger
on: push

# you can set multiple jobs
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        # using checkout actions 
        - name: checkout
          uses: actions/checkout@v4

        - name: List and REad Files
          run: |
            echo "First Github action job"
            ls -lart
            cat README.md

