name: multijob
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: create directory
              run: |
                echo "hello world ! " >> helloworld.txt
            - name: upload to artifact
              uses: actions/upload-artifact@v4
              with:
                name: helloworld text file
                path: helloworld.txt
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: go to files
              run: |
                cat helloworld.txt