name: multijob
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: create directory
              run: |
                mkdir abinash
    job2:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: cd mkdir